services:
  # MySQL Database for SuiteCRM
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: suitecrm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_PASSWORD: suitecrm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
    networks:
      - suitecrm-network

  # SuiteCRM Backend (PHP + Apache)
  suitecrm:
    build:
      context: ./docker/suitecrm
      dockerfile: Dockerfile
    container_name: suitecrm-backend
    ports:
      - "8080:80"
    volumes:
      # Core SuiteCRM
      - ./backend/suitecrm:/var/www/html:rw
      
      # Mount our custom code into SuiteCRM structure
      - ./backend/custom/api:/var/www/html/custom/api:rw
      - ./backend/custom/Extension:/var/www/html/custom/Extension:rw
      - ./backend/custom/modules:/var/www/html/custom/modules:rw
      - ./backend/custom/services:/var/www/html/custom/services:rw
      - ./backend/custom/public:/var/www/html/public/custom:rw
      
      # Config override
      - ./backend/custom/config/config_override.php:/var/www/html/config_override.php:rw
      
      # Tests and environment
      - ./backend/tests:/var/www/html/tests:rw
      - ./backend/.env:/var/www/html/.env:ro
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: suitecrm
      DATABASE_USER: suitecrm
      DATABASE_PASSWORD: suitecrm
      SUITECRM_URL: http://localhost:8080
      SUITECRM_DATABASE_DRIVER: mysql
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - suitecrm-network
    restart: unless-stopped

  # React Frontend  
  # frontend:
  #   build:
  #     context: ./docker/frontend
  #     dockerfile: Dockerfile
  #   container_name: suitecrm-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app:rw
  #     - /app/node_modules
  #   environment:
  #     VITE_SUITECRM_URL: http://localhost:8080
  #     VITE_SUITECRM_CLIENT_ID: suitecrm_client
  #   depends_on:
  #     suitecrm:
  #       condition: service_healthy
  #   networks:
  #     - suitecrm-network
  #   restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - suitecrm-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  suitecrm-network:
    driver: bridge